services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: guntan
      POSTGRES_PASSWORD: guntan
      POSTGRES_DB: guntan
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U guntan"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  meilisearch:
    image: getmeili/meilisearch:v1.11
    environment:
      MEILI_MASTER_KEY: dev_meili_master_key_change_me
      MEILI_ENV: development
    ports:
      - "7700:7700"
    volumes:
      - meilidata:/meili_data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio-secret
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      mc alias set local http://minio:9000 minio minio-secret;
      mc mb -p local/guntan-media || true;
      mc anonymous set download local/guntan-media;
      exit 0;
      "

volumes:
  pgdata:
  meilidata:
  miniodata:
