server {
  listen 80;
  server_name guntan.localhost japon.localhost alman.localhost italy.localhost fransa.localhost abd.localhost kore.localhost;
  location / {
    proxy_pass http://storefront:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
server {
  listen 80;
  server_name localhost;
  location / {
    proxy_pass http://admin:3001;
    proxy_set_header Host $host;
  }
}
